# Form implementation generated from reading ui file 'votingapp_gui.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
import PyQt6.QtWidgets
from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtGui import QFont
from PyQt6.QtWidgets import QMessageBox, QApplication
import pyqtgraph
import sys

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 450)
        MainWindow.setMinimumSize(QtCore.QSize(400, 450))
        MainWindow.setMaximumSize(QtCore.QSize(400, 450))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.title_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.title_label.setGeometry(QtCore.QRect(40, -10, 321, 61))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.title_label.setFont(font)
        self.title_label.setAutoFillBackground(False)
        self.title_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.title_label.setObjectName("title_label")
        self.option1_radio = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.option1_radio.setGeometry(QtCore.QRect(120, 130, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.option1_radio.setFont(font)
        self.option1_radio.setObjectName("option1_radio")
        self.buttonGroup = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.option1_radio)
        self.option2_radio = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.option2_radio.setGeometry(QtCore.QRect(120, 170, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.option2_radio.setFont(font)
        self.option2_radio.setObjectName("option2_radio")
        self.buttonGroup.addButton(self.option2_radio)
        self.optionother_radio = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.optionother_radio.setGeometry(QtCore.QRect(120, 210, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.optionother_radio.setFont(font)
        self.optionother_radio.setObjectName("optionother_radio")
        self.buttonGroup.addButton(self.optionother_radio)
        self.voterid_textentry = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.voterid_textentry.setGeometry(QtCore.QRect(180, 70, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Myanmar Text")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.voterid_textentry.setFont(font)
        self.voterid_textentry.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.voterid_textentry.setText("")
        self.voterid_textentry.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.voterid_textentry.setObjectName("voterid_textentry")
        self.voter_id_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.voter_id_label.setGeometry(QtCore.QRect(50, 70, 120, 31))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.voter_id_label.setFont(font)
        self.voter_id_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.voter_id_label.setObjectName("voter_id_label")
        self.other_textentry = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.other_textentry.setEnabled(True)
        self.other_textentry.setGeometry(QtCore.QRect(180, 260, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Myanmar Text")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.other_textentry.setFont(font)
        self.other_textentry.setText("")
        self.other_textentry.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.other_textentry.setClearButtonEnabled(False)
        self.other_textentry.setObjectName("other_textentry")
        self.other_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.other_label.setEnabled(True)
        self.other_label.setGeometry(QtCore.QRect(20, 250, 171, 51))
        self.other_label.setVisible(False)
        self.other_textentry.setVisible(False)
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.other_label.setFont(font)
        self.other_label.setObjectName("other_label")
        self.save_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.save_button.setEnabled(False)
        self.save_button.setGeometry(QtCore.QRect(100, 310, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.save_button.setFont(font)
        self.save_button.setObjectName("save_button")
        self.clear_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.clear_button.setGeometry(QtCore.QRect(220, 310, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        self.clear_button.setFont(font)
        self.clear_button.setObjectName("clear_button")
        self.results_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.results_button.setGeometry(QtCore.QRect(130, 350, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        self.results_button.setFont(font)
        self.results_button.setObjectName("results_button")
        self.line = QtWidgets.QFrame(parent=self.centralwidget)
        self.line.setGeometry(QtCore.QRect(70, 40, 251, 20))
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setObjectName("line")
        self.exit_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.exit_button.setGeometry(QtCore.QRect(160, 380, 75, 23))
        self.exit_button.setObjectName("exit_button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 400, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.title_label.setText(_translate("MainWindow", "Voting Application"))
        self.option1_radio.setText(_translate("MainWindow", "Pro-Skub"))
        self.option2_radio.setText(_translate("MainWindow", "Anti-Skub"))
        self.optionother_radio.setText(_translate("MainWindow", "Other"))
        self.voter_id_label.setText(_translate("MainWindow", "Voter ID #:"))
        self.other_label.setText(_translate("MainWindow", "Other (Specify): "))
        self.save_button.setText(_translate("MainWindow", "Save"))
        self.clear_button.setText(_translate("MainWindow", "Clear"))
        self.results_button.setText(_translate("MainWindow", "View Current Results"))
        self.exit_button.setText(_translate("MainWindow", "Exit"))

    def show_error_popup(self, error_code: int) -> None:
        """
        Generates popup error box based on error code.
        :param error_code: error code specified by code in logic.py
        :return: None
        """
        popup = QMessageBox()
        popup.setWindowTitle('Error!')
        popup.setIcon(QMessageBox.Icon.Warning)
        popup.setStandardButtons(QMessageBox.StandardButton.Ok)
        if error_code == 1:
            popup.setText('ERROR: Voter ID already in use. Please try again.')
        elif error_code == 2:
            popup.setText('ERROR: Voter ID consists of only numbers. Please try again.')
        popup.exec()

    def show_chart_window(self, vote_dict: dict) -> None:
        """
        Draws and generates bar graph representing the current vote count based on vote_dict.
        :param vote_dict: Updated dictionary of votes passed from logic.py.
        :return: None
        """
        vote_tally = {}
        x_axis = []
        x_values = []
        y_axis = []
        for vote in vote_dict:
            if vote_dict[vote] in vote_tally:
                vote_tally[vote_dict[vote]] += 1
            else:
                vote_tally[vote_dict[vote]] = 1
        for candidate in vote_tally:
            x_axis.append(candidate)
            y_axis.append(vote_tally[candidate])
        for num in range(len(x_axis)):
            x_values.append(num+1)

        self.graph_window = pyqtgraph.PlotWidget()
        self.graph_window.setWindowTitle('Current Vote Results')
        self.graph_window.setLabel('bottom', 'Candidates')
        self.graph_window.setLabel('left', 'Number of Votes')
        self.graph_window.setYRange(0, max(y_axis))
        self.graph_window.setMinimumSize(500,600)
        self.graph_window.setMaximumSize(500,600)

        graph = pyqtgraph.BarGraphItem(x=x_values, y1=y_axis, width=0.6, brush='b')

        self.graph_window.addItem(graph)

        vertical_axis = self.graph_window.getAxis('left')
        vertical_axis.label.setFont(QFont("Times", 18))

        horizontal_axis = self.graph_window.getAxis('bottom')
        horizontal_axis.setTicks([list(zip(x_values, x_axis))])
        horizontal_axis.label.setFont(QFont("Times", 18))

        self.graph_window.setEnabled(False)
        self.graph_window.show()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
